theory Prop31short
	imports Geometry Prop31
begin

theorem(in euclidean_geometry) Prop31short:
	assumes 
		"bet B D C"
		"\<not> col B C A"
	shows "\<exists> E F S. bet E A F \<and> ang_eq E A D A D C \<and> parallel E F B C \<and> bet E S C \<and> bet A S D"
proof -
	obtain E F S where "bet E A F \<and> ang_eq F A D A D B \<and> ang_eq F A D B D A \<and> ang_eq D A F B D A \<and> ang_eq E A D A D C \<and> ang_eq E A D C D A \<and> ang_eq D A E C D A \<and> parallel E F B C \<and> seg_eq E A D C \<and> seg_eq A F B D \<and> seg_eq A S S D \<and> seg_eq E S S C \<and> seg_eq B S S F \<and> bet E S C \<and> bet B S F \<and> bet A S D" using Prop31[OF `bet B D C` `\<not> col B C A`]  by  blast
	have "bet E A F" using `bet E A F \<and> ang_eq F A D A D B \<and> ang_eq F A D B D A \<and> ang_eq D A F B D A \<and> ang_eq E A D A D C \<and> ang_eq E A D C D A \<and> ang_eq D A E C D A \<and> parallel E F B C \<and> seg_eq E A D C \<and> seg_eq A F B D \<and> seg_eq A S S D \<and> seg_eq E S S C \<and> seg_eq B S S F \<and> bet E S C \<and> bet B S F \<and> bet A S D` by blast
	have "ang_eq E A D A D C" using `bet E A F \<and> ang_eq F A D A D B \<and> ang_eq F A D B D A \<and> ang_eq D A F B D A \<and> ang_eq E A D A D C \<and> ang_eq E A D C D A \<and> ang_eq D A E C D A \<and> parallel E F B C \<and> seg_eq E A D C \<and> seg_eq A F B D \<and> seg_eq A S S D \<and> seg_eq E S S C \<and> seg_eq B S S F \<and> bet E S C \<and> bet B S F \<and> bet A S D` by blast
	have "parallel E F B C" using `bet E A F \<and> ang_eq F A D A D B \<and> ang_eq F A D B D A \<and> ang_eq D A F B D A \<and> ang_eq E A D A D C \<and> ang_eq E A D C D A \<and> ang_eq D A E C D A \<and> parallel E F B C \<and> seg_eq E A D C \<and> seg_eq A F B D \<and> seg_eq A S S D \<and> seg_eq E S S C \<and> seg_eq B S S F \<and> bet E S C \<and> bet B S F \<and> bet A S D` by blast
	have "bet E S C" using `bet E A F \<and> ang_eq F A D A D B \<and> ang_eq F A D B D A \<and> ang_eq D A F B D A \<and> ang_eq E A D A D C \<and> ang_eq E A D C D A \<and> ang_eq D A E C D A \<and> parallel E F B C \<and> seg_eq E A D C \<and> seg_eq A F B D \<and> seg_eq A S S D \<and> seg_eq E S S C \<and> seg_eq B S S F \<and> bet E S C \<and> bet B S F \<and> bet A S D` by blast
	have "bet A S D" using `bet E A F \<and> ang_eq F A D A D B \<and> ang_eq F A D B D A \<and> ang_eq D A F B D A \<and> ang_eq E A D A D C \<and> ang_eq E A D C D A \<and> ang_eq D A E C D A \<and> parallel E F B C \<and> seg_eq E A D C \<and> seg_eq A F B D \<and> seg_eq A S S D \<and> seg_eq E S S C \<and> seg_eq B S S F \<and> bet E S C \<and> bet B S F \<and> bet A S D` by blast
	have "bet E A F \<and> ang_eq E A D A D C \<and> parallel E F B C \<and> bet E S C \<and> bet A S D" using `bet E A F \<and> ang_eq F A D A D B \<and> ang_eq F A D B D A \<and> ang_eq D A F B D A \<and> ang_eq E A D A D C \<and> ang_eq E A D C D A \<and> ang_eq D A E C D A \<and> parallel E F B C \<and> seg_eq E A D C \<and> seg_eq A F B D \<and> seg_eq A S S D \<and> seg_eq E S S C \<and> seg_eq B S S F \<and> bet E S C \<and> bet B S F \<and> bet A S D` `bet E A F \<and> ang_eq F A D A D B \<and> ang_eq F A D B D A \<and> ang_eq D A F B D A \<and> ang_eq E A D A D C \<and> ang_eq E A D C D A \<and> ang_eq D A E C D A \<and> parallel E F B C \<and> seg_eq E A D C \<and> seg_eq A F B D \<and> seg_eq A S S D \<and> seg_eq E S S C \<and> seg_eq B S S F \<and> bet E S C \<and> bet B S F \<and> bet A S D` `bet E A F \<and> ang_eq F A D A D B \<and> ang_eq F A D B D A \<and> ang_eq D A F B D A \<and> ang_eq E A D A D C \<and> ang_eq E A D C D A \<and> ang_eq D A E C D A \<and> parallel E F B C \<and> seg_eq E A D C \<and> seg_eq A F B D \<and> seg_eq A S S D \<and> seg_eq E S S C \<and> seg_eq B S S F \<and> bet E S C \<and> bet B S F \<and> bet A S D` `bet E A F \<and> ang_eq F A D A D B \<and> ang_eq F A D B D A \<and> ang_eq D A F B D A \<and> ang_eq E A D A D C \<and> ang_eq E A D C D A \<and> ang_eq D A E C D A \<and> parallel E F B C \<and> seg_eq E A D C \<and> seg_eq A F B D \<and> seg_eq A S S D \<and> seg_eq E S S C \<and> seg_eq B S S F \<and> bet E S C \<and> bet B S F \<and> bet A S D` `bet E A F \<and> ang_eq F A D A D B \<and> ang_eq F A D B D A \<and> ang_eq D A F B D A \<and> ang_eq E A D A D C \<and> ang_eq E A D C D A \<and> ang_eq D A E C D A \<and> parallel E F B C \<and> seg_eq E A D C \<and> seg_eq A F B D \<and> seg_eq A S S D \<and> seg_eq E S S C \<and> seg_eq B S S F \<and> bet E S C \<and> bet B S F \<and> bet A S D` by blast
	thus ?thesis by blast
qed

end